
***** CORRELACION
DATASET ACTIVATE Conjunto_de_datos1.
CORRELATIONS
  /VARIABLES=VAR_DEP SAL_VENCIDO_N
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

DATASET ACTIVATE Conjunto_de_datos1.
CORRELATIONS
  /VARIABLES=VAR_DEP EDAD
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

